### ISSUE TITLE
additionalProp1 on FastApi > 0.99 (OpenAPI 3.1.0)

### ISSUE THREAD

**Issue by noxxer** [smagafurov/fastapi-jsonrpc#51] opened 2023-07-12 11:52 UTC
FastApi adds the 'additionalProp1' field to the example code during tryout, which naturally does not pass validation during execution.

there is no problem on version 0.97.0

**Comment by spumer** [comment] 2023-07-12 17:56
I think this problem related to OpenAPI 3.1.0: https://github.com/smagafurov/fastapi-jsonrpc/issues/45#issuecomment-1617666387 and reproduced since FastAPI 0.99.0

**Comment by spumer** [comment] 2023-09-09 05:28
Fixed in new fastapi versions
<img width="481" alt="additionalprops" src="https://github.com/smagafurov/fastapi-jsonrpc/assets/735150/3341b37a-37a2-4159-b5f1-c710000e25f7">

**Closed by spumer** 2023-09-09 05:28 UTC
Labels: bug
